### PR TITLE
Csvlint validation

### PR DESCRIPTION
**Pull request by bcouston**

### CODE REVIEW

**Comment by bcouston** [comment]
@pezholio and @quadrophobiac can you review this please before we merge?

**Comment by bcouston** [comment]
Currently outputs errors, warnings and info messages into console

**Comment by pezholio** [comment]
That's awesome :+1: 

Can you add the validate CSV button as a menu item instead though?

Should be a simple case of adding a menu item to `main.js`, which triggers an ipc event in `hot.js`, which then triggers the function.

**Comment by bcouston** [comment]
Links to issue #2

**Pull request merged**
