### PR TITLE
Import Excel files

### LINKED ISSUE #6: Import excel files
As a CSV editor
I want to import my initial data from Excel
So I can work on exporting it as a correctly-formatted CSV

### PR DESCRIPTION
**Pull request by pezholio**
Fixes #6

### CODE REVIEW

**Comment by bcouston** [comment]
I'm getting a cannot find module 'xlxs' message upon attempting to start the app. Will figure out tomorrow.

**Comment by pezholio** [comment]
Ah yeah, try another `npm install`

**Comment by pezholio** [comment]
After having a bit of a play, I've noticed that when importing subsequent Excel files after already importing one, extra browser windows get spawned for some reason. Don't merge this yet, while I get it fixed.

**Comment by pezholio** [comment]
Thanks @danielgavrilov - that now works! :smile:

**Pull request merged**
